NATO = {
    'a' : "Arlo",
    'b' : "Bandit",
    'c' : "Clifford",
    'd' : "Daisy",
    'e' : "Ellie",
    'f' : "Fritz",
    'g' : "Gibs",
    'h' : "Harley",
    'i' : "India",
    'j' : "Jasper",
    'k' : "Kilo",
    'l' : "Lima",
    'm' : "Milo",
    'n' : "Nacho",
    'o' : "Oscar",
    'p' : "Pluto",
    'q' : "Quinn",
    'r' : "Ruger",
    's' : "Sampson",
    't' : "Toto",
    'u' : "Ulysses",
    'v' : "Victor",
    'w' : "Whisky",
    'x' : "Xavier",
    'y' : "Yankee",
    'z' : "Zulu",


    'A' : "Ace",
    'B' : "Bo",
    'C' : "Chip",
    'D' : "Dumbo",
    'E' : "Einstein",
    'F' : "Fido",
    'G' : "Gromit",
    'H' : "Hooch",
    'I' : "Itchy",
    'J' : "Jack",
    'K' : "Kipper",
    'L' : "Lassie",
    'M' : "Max",
    'N' : "Napoleon",
    'O' : "Odie",
    'P' : "Pickles",
    'Q' : "Quincy",
    'R' : "Rover",
    'S' : "Snoopy",
    'T' : "Togo",
    'U' : "Umar",
    'V' : "Vincent",
    'W' : "Wishbone",
    'X' : "Xeno",
    'Y' : "Yoda",
    'Z' : "Zeus"
    }

STATES = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DC", "DE", "FL", "GA",
          "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
          "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
          "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC",
          "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]

CANADA = ['AB','BC','MB','NB','NL','NT','NS','NU','ON','PE','QC','SK','YT']



LIST_OF_BREEDS = ['Affenpinscher', 'Afghan Hound', 'Airedale Terrier', 'Akbash',
'Akita', 'Alaskan Malamute', 'American Bulldog', 'American Eskimo Dog',
'American Hairless Terrier', 'American Staffordshire Terrier',
'American Water Spaniel', 'Anatolian Shepherd', 'Appenzell Mountain Dog',
'Australian Cattle Dog / Blue Heeler', 'Australian Kelpie',
'Australian Shepherd', 'Australian Terrier', 'Basenji', 'Basset Hound',
'Beagle', 'Bearded Collie', 'Beauceron', 'Belgian Shepherd / Laekenois',
'Belgian Shepherd / Malinois', 'Belgian Shepherd / Sheepdog',
'Belgian Shepherd / Tervuren', 'Bernese Mountain Dog', 'Bichon Frise',
'Black and Tan Coonhound', 'Black Labrador Retriever', 'Black Mouth Cur',
'Black Russian Terrier', 'Bloodhound', 'Blue Lacy', 'Bluetick Coonhound',
'Boerboel', 'Bolognese', 'Border Collie', 'Border Terrier', 'Borzoi',
'Boston Terrier', 'Bouvier des Flanders', 'Boxer', 'Boykin Spaniel', 'Briard',
'Brittany Spaniel', 'Brussels Griffon', 'Bull Terrier', 'Bullmastiff',
'Cairn Terrier', 'Canaan Dog', 'Cane Corso Mastiff', 'Carolina Dog',
'Catahoula Leopard Dog', 'Cattle Dog',
'Caucasian Sheepdog / Caucasian Ovtcharka', 'Cavalier King Charles Spaniel',
'Chesapeake Bay Retriever', 'Chihuahua', 'Chinese Crested Dog', 'Chinook',
'Chocolate Labrador Retriever', 'Chow Chow', 'Clumber Spaniel', 'Cockapoo',
'Cocker Spaniel', 'Collie', 'Coonhound', 'Corgi', 'Coton de Tulear',
'Curly-Coated Retriever', 'Dachshund', 'Dalmatian', 'Dandi Dinmont Terrier',
'Doberman Pinscher', 'Dogo Argentino', 'Dogue de Bordeaux', 'Dutch Shepherd',
'English Bulldog', 'English Cocker Spaniel', 'English Coonhound',
'English Pointer', 'English Setter', 'English Shepherd',
'English Springer Spaniel', 'English Toy Spaniel', 'Entlebucher', 'Eskimo Dog',
'Feist', 'Field Spaniel', 'Fila Brasileiro', 'Finnish Spitz',
'Flat-Coated Retriever', 'Fox Terrier', 'Foxhound', 'French Bulldog',
'Galgo Spanish Greyhound', 'German Pinscher', 'German Shepherd Dog',
'German Shorthaired Pointer', 'German Spitz', 'German Wirehaired Pointer',
'Giant Schnauzer', 'Glen of Imaal Terrier', 'Golden Retriever', 'Gordon Setter',
'Great Dane', 'Great Pyrenees', 'Greater Swiss Mountain Dog', 'Greyhound',
'Hamiltonstovare', 'Harrier', 'Havanese', 'Hound', 'Hovawart', 'Husky',
'Ibizan Hound', 'Irish Setter', 'Irish Terrier', 'Irish Wolfhound',
'Italian Greyhound', 'Italian Spinone', 'Jack Russell Terrier',
'Jack Russell Terrier (Parson)', 'Japanese Chin', 'Jindo', 'Kai Dog',
'Karelian Bear Dog', 'Keeshond', 'Kerry Blue Terrier', 'Kishu', 'Klee Kai',
'Komondor', 'Kuvasz', 'Kyi Leo', 'Labrador Retriever', 'Lakeland Terrier',
'Lancashire Heeler', 'Leonberger', 'Lhasa Apso', 'Lowchen', 'Maltese',
'Manchester Terrier', 'Maremma Sheepdog', 'Mastiff', 'McNab',
'Miniature Pinscher', 'Miniature Schnauzer', 'Mixed Breed',
'Mountain Cur', 'Mountain Dog', 'Munsterlander', 'Neapolitan Mastiff',
'Newfoundland Dog', 'Norfolk Terrier', 'Norwegian Elkhound',
'Norwegian Lundehund', 'Norwich Terrier', 'Nova Scotia Duck Tolling Retriever',
'Old English Sheepdog', 'Otterhound', 'Papillon',
'Patterdale Terrier / Fell Terrier', 'Pekingese', 'Peruvian Inca Orchid',
'Petit Basset Griffon Vendeen', 'Pharaoh Hound', 'Pit Bull Terrier',
'Plott Hound', 'Podengo Portugueso', 'Pointer', 'Pomeranian', 'Poodle',
'Portuguese Water Dog', 'Presa Canario', 'Pug', 'Rat Terrier',
'Redbone Coonhound', 'Retriever', 'Rhodesian Ridgeback', 'Rottweiler',
'Rough Collie', 'Saint Bernard / St. Bernard', 'Saluki', 'Samoyed',
'Schipperke', 'Schnauzer', 'Scottish Deerhound', 'Scottish Terrier Scottie',
'Sealyham Terrier', 'Setter', 'Shar Pei', 'Sheep Dog', 'Shepherd',
'Shetland Sheepdog Sheltie', 'Shiba Inu', 'Shih Tzu', 'Siberian Husky',
'Silky Terrier', 'Skye Terrier', 'Sloughi', 'Smooth Collie',
'Smooth Fox Terrier', 'Spaniel', 'Spitz', 'Staffordshire Bull Terrier',
'Standard Poodle', 'Standard Schnauzer', 'Sussex Spaniel', 'Swedish Vallhund',
'Terrier', 'Thai Ridgeback', 'Tibetan Mastiff', 'Tibetan Spaniel',
'Tibetan Terrier', 'Tosa Inu', 'Toy Fox Terrier', 'Treeing Walker Coonhound',
'Vizsla', 'Weimaraner', 'Welsh Corgi', 'Welsh Springer Spaniel',
'Welsh Terrier', 'West Highland White Terrier Westie', 'Wheaten Terrier',
'Whippet', 'White German Shepherd', 'Wire Fox Terrier',
'Wirehaired Dachshund', 'Wirehaired Pointing Griffon', 'Wirehaired Terrier',
'Xoloitzcuintle / Mexican Hairless', 'Yellow Labrador Retriever',
'Yorkshire Terrier Yorkie']
